name: Windows build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  TARGET: Utils

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -v --target ${{env.TARGET}}

    - name: Archive Artifacts
      run: Compress-Archive -Path build/bin/* -DestinationPath ${{env.TARGET}}-${{env.BUILD_TYPE}}.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.TARGET}}-${{env.BUILD_TYPE}}
        path: ${{env.TARGET}}-${{env.BUILD_TYPE}}.zip