name: Linux build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  TARGET: Utils

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/bin

    - name: Build
      run: cmake --build ${{github.workspace}}/bin --config ${{env.BUILD_TYPE}} 

    - name: Archive Artifacts
      run: zip -r ${{env.TARGET}}-${{env.BUILD_TYPE}}.zip bin

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.TARGET}}-${{env.BUILD_TYPE}}
        path: ${{env.TARGET}}-${{env.BUILD_TYPE}}.zip